EXE = main
OBJS = main.o
CLEAN_RM =

include ../_make/generic.mk

# Additional dependencies for the object files:
# (If you edit any of these files, then doing "make" will trigger a rebuild.)
$(OBJS): AVL.h AVL.hpp AVL-extra.hpp
